import { Plus_Jakarta_Sans, Fraunces } from "next/font/google";
import Navbar from "@/components/layouts/Navbar";
import "./globals.css";
import Footer from "@/components/layouts/Footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} ${fraunces.variable} h-full antialiased`}
      data-theme="light"
    >
      <body className="font-sans min-h-full flex flex-col">
        <Navbar />

        <main>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
